@startuml
actor Chef
participant Controller
participant ChefService
participant ChefRepository
participant Database

Chef -> Controller : Gửi yêu cầu tự cập nhật profile
Controller -> ChefService : updateChefBySelf(userId, requestDto)

ChefService -> ChefRepository : findByUserId(userId)
ChefRepository -> Database : Execute
Database --> ChefRepository : Chef
ChefRepository --> ChefService : Chef

ChefService -> ChefRepository : save(Chef đã cập nhật)
ChefRepository -> Database : Update
Database --> ChefRepository : Chef
ChefRepository --> ChefService : Chef

ChefService --> Controller : Trả về ChefResponseDto
Controller --> Chef : ChefResponseDto
@enduml
