version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_vietchef
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: vietchef
      MYSQL_USER: vietchef_user
      MYSQL_PASSWORD: vietchef_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vietchef_network

  spring_app:
    build: .
    container_name: vietchef_app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vietchef?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: vietchef_user
      SPRING_DATASOURCE_PASSWORD: vietchef_pass
      VIRTUAL_HOST: vietchef-api.ddns.net
      LETSENCRYPT_HOST: vietchef-api.ddns.net
      LETSENCRYPT_EMAIL: thieuphong2003@gmail.com
    expose:
      - "8080"
    networks:
      - vietchef_network
      - nginx_proxy


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf
    networks:
      - nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx_proxy
      DEFAULT_EMAIL: thieuphong2003@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - nginx_proxy

volumes:
  mysql_data:
  nginx_certs:
  nginx_vhost:
  nginx_html:

networks:
  vietchef_network:
  nginx_proxy:
