spring.application.name=vietchefs

spring.datasource.url=jdbc:mysql://localhost:3306/vietchef1
spring.datasource.username=root
spring.datasource.password=12345
#spring.datasource.url=jdbc:mysql://34.126.92.224:3307/vietchef?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
##spring.datasource.username=vietchef_user
##spring.datasource.password=vietchef_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG


app.jwt.private-key-location=classpath:keys/private.pem
app.jwt.public-key-location=classpath:keys/public.pem
app.jwt-access-expiration-seconds=3600
app.jwt-refresh-expiration-seconds=360000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thieuphongfo4@gmail.com
spring.mail.password=ccvv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=500


google.maps.api.key=${GOOGLE}

paypal.api.base-url=https://api-m.sandbox.paypal.com
paypal.client.id=${GOOGLE}
paypal.client.secret=${GOOGLE}
paypal.mode=sandbox

azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=vietchef2003;AccountKey=VEg7QPfBzXiJI5ga7QbU5MADKk3oVP3XNwFWU6r+DBYXi2ZI5ao6TROww58ecWIurLQdYDZsefex+AStrJvAuQ==;EndpointSuffix=core.windows.net
azure.storage.container-name=vietchefimage

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Google OAuth
oauth.google.client-id=${GOOGLE}
oauth.google.client-secret=${GOOGLE}
#oauth.google.redirect-uri=https://grammar-456201-n8.firebaseapp.com/__/auth/handler
#oauth.google.redirect-uri=https://vietchef-api.ddns.net/no-auth/google/callback
oauth.google.redirect-uri=https://vietchef-api.myddns.me/no-auth/google/callback
outbound.identity.client-id=${GOOGLE}
outbound.identity.client-secret=${GOOGLE}
outbound.identity.redirect-uri=http://localhost:3000/authenticate

# Facebook OAuth
oauth.facebook.client-id=${GOOGLE}
oauth.facebook.client-secret=${GOOGLE}
#oauth.facebook.redirect-uri=https://vietchef-api.ddns.net/no-auth/facebook/callback
oauth.facebook.redirect-uri=https://vietchef-api.myddns.me/no-auth/facebook/callback

#Vertex AI
spring.ai.vertex.ai.embedding.project-id=adept-box-459205-u4
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.gemini.project-id=adept-box-459205-u4
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.embedding.text.options.model=text-embedding-004
spring.ai.vertex.ai.gemini.model-name=gemini-2.0-flash






