name: Deploy to GCP

on:
  push:
    branches: [deploy-gg]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GCP Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USERNAME@$SERVER_IP << 'EOF'
              cd ~/vietchef || {git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/phongkhongxai/vietchef.git && cd vietchef;}
              cd vietchef
              git fetch --all
              git reset --hard origin/deploy-gg
              git pull origin deploy-gg
              mvn clean package -DskipTests   
              sudo docker-compose down
              sudo docker-compose up -d --build
          EOF